// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace WorldTrotter
{
	public partial class ConversionViewController : UIViewController
	{
		public ConversionViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
