// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace WorldTrotter
{
	public partial class InternetViewController : UIViewController
	{
		public InternetViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			var webView = View as UIWebView;
			if (webView != null)
			{
				webView.LoadRequest(new NSUrlRequest(new NSUrl("https://www.bignerdranch.com")));
			}
		}
	}
}
